### ISSUE TITLE
Usagse about Scaffold_decoration_examples 

### ISSUE THREAD

**Issue by XiaoYT97** [MingyuanXu/Tree-Invent#2]
Hi, I'm interested in the  Scaffold_decoration using tree invent model. When I run the sample.py or rl.py file, it said that  <No such file or directory: 'MFTs_Gen_Model.zip'>. So how can I get it, is there something to do first ?

**Comment by MingyuanXu** [comment]
Sorry, the reply is late. the MFTs_Gen_Model are located in Tree-Invent/pretrained_models,  It should be zipped as MFTs_Gen_Model.zip for scaffold_decoration computations.

**Comment by XiaoYT97** [comment]
Thank you for the reply, but sorry about that i still cannot find MFTs_Gen_Model.zip  in Tree-Invent/pretrained_models. Is it generated after something operation of specfic scripts? Otherwise, could you please check about whether the file was missing during the project upload process? 
![Tag](https://github.com/MingyuanXu/Tree-Invent/assets/68654244/20f44044-6a6c-4685-b13f-72cf26f09122)

**Comment by MingyuanXu** [comment]
Due to the file size limitation in Github, I uploaded the directory of
MFTs_Gen_Model, which is unzipped from MFTs_Gen_Model.zip,  instead of
MFTs_Gen_Model.zip,  For any example in Tree-Invent Community, you should
zip the directory of MFTs_Gen_Model in pretrained_models firstly, and move
it to your work directory, then everything will be fine.

**Comment by MingyuanXu** [comment]
If you are still confused about MFTs_Gen_Model.zip, please go to TreeInvent/pretrained_models, and use this script named zip.py:
`
import shutil;
shutil.make_archive('MFTs_Gen_Model',"zip",'MFTs_Gen_Model')
`
run the command `python zip.py`, then you get the MFTs_Gen_Model.zip.

**Comment by XiaoYT97** [comment]
Thank you for all of that , I have got it very clearly ! ^_^
